# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

parameters:
- name: REPO_CLONE
  default: ''  
- name: AZ_SUBSCRIPTION
  default: '' 
- name: AZ_RESOURCE_GROUP
  default: '' 
- name: AKS_CLUSTER
  default: '' 
- name: commands
  default: '' 
- name: arguments
  default: '' 


resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker'
        repository: 'bala2805/k8s_project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: Kubernetes@1
      displayName: kubectl apply using arguments
      inputs:
        azureSubscription: ${{ parameters.AZ_SUBSCRIPTION }}
        azureResourceGroup:  ${{ parameters.AZ_RESOURCE_GROUP }}
        kubernetesCluster:  ${{ parameters.AKS_CLUSTER }}
        command: ${{ parameters.commands }}
        arguments: ${{ parameters.arguments }}
