# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

parameters:
- name: BUILD
  type: boolean
  default: true
- name: DEPLOY
  type: boolean
  default: true
- name: serviceConnection
  default: '' 
- name: nameSpace
  default: '' 
- name: commands
  default: '' 
- name: arguments
  default: '' 


resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - ${{ if eq(parameters.BUILD, true) }}:
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker'
          repository: 'bala2805/k8s_project'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(tag)
   
  - ${{ if eq(parameters.DEPLOY, true) }}:          
    - job: DEPLOY
      dependsOn:
        - Build
      displayName: DEPLOY
      pool:
        vmImage: 'ubuntu-latest'
      steps: 
      - task: Kubernetes@1
        displayName: kubectl apply using arguments
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: ${{ parameters.serviceConnection }}
          namespace: ${{ parameters.nameSpace }}
          command: ${{ parameters.commands }}
          arguments: -f  ${{ parameters.arguments }}
