apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
 type: ClusterIP
 ports:
  - port: 8080
    targetPort: ${TARGETPORT}
 selector:
   app: hello-world-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
 replicas: ${REPLICAS}
 selector:
   matchLabels:
    app: hello-world-app
 template:
   metadata:
    labels:
     app: hello-world-app
   spec:
    containers:
      - name: hello-world
        image: ${IMAGE}
        ports:
        - containerPort: ${CONTAINERPORT}
    
